# Specify version format
version: "1.0.0.{build}"

# Image to use
image: Visual Studio 2017

# Branches to build
branches:
  only: 
    - master

# Including commits with 'build' comment
only_commits:
  message: build

# Build matrix
environment:
  matrix:
    - type: MinGW
      build: call mingw.bat
      command: cmd /C
    - type: VisualStudio
      build: call vs.bat
      command: cmd /C

# Allow to fail on first error in matrix
matrix:
  fast_finish: true

# Scripts that run after cloning repository
install:
  # Chocolatey
  - choco upgrade chocolatey
  # MinGW
  - if "%type%"=="MinGW" if not exist "C:\mingw.7z" appveyor-retry appveyor DownloadFile "http://downloads.sourceforge.net/mingw-w64/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z" -FileName "C:\mingw.7z"
  - if "%type%"=="MinGW" 7z x -y -oC:\ "C:\mingw.7z" > nul
  - if "%type%"=="MinGW" set PATH=C:\mingw64\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - if "%type%"=="MinGW" set INCLUDE=C:\mingw64\x86_64-w64-mingw32\include;%INCLUDE%
  # Visual Studio
  - if "%type%"=="VisualStudio" set INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared;%INCLUDE%
  - if "%type%"=="VisualStudio" set LIB=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x64;%LIB%
  # CMake
  - '%command% "cmake --version"'
  # gil
  - set PATH=C:\Python37;C:\Python37\Scripts;%PATH%
  - pip3 install gil
  - gil update

# Build scripts
build_script:
  - cd build
  - '%build%'

# Test scripts
test: off
