# Specify version format
version: "1.0.0.{build}"

# Image to use
image: Visual Studio 2017

# Branches to build
branches:
  only: 
    - master

# Including commits with 'build' comment
only_commits:
  message: build

# Cache files to speed up build
cache:
    - C:\mingw.7z -> .appveyor.yml
    - C:\cache\cygwin -> .appveyor.yml

# Build matrix
environment:
  matrix:
    - type: Cygwin
      build: C:\cygwin64\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/build; exec 0</dev/null; ./cygwin.sh"
      command: C:\cygwin64\bin\bash -lc
    - type: MinGW
      build: call mingw.bat
      command: cmd /C
    - type: VisualStudio
      build: call vs.bat
      command: cmd /C

# Allow to fail on first error in matrix
matrix:
  fast_finish: true

# Scripts that run after cloning repository
install:
  # Chocolatey
  - choco upgrade chocolatey
  # Doxygen
  - choco install --cache "C:\ProgramData\chocolatey\cache" --force doxygen.portable
  - choco install --cache "C:\ProgramData\chocolatey\cache" --force ghostscript
  - choco install --cache "C:\ProgramData\chocolatey\cache" --force graphviz
  - choco install --cache "C:\ProgramData\chocolatey\cache" --force miktex
  # Cygwin
  - if "%type%"=="Cygwin" if not exist "C:\cygwin64" mkdir "C:\cygwin64"
  - if "%type%"=="Cygwin" appveyor-retry appveyor DownloadFile "http://cygwin.com/setup-x86_64.exe" -FileName "C:\cygwin64\setup-x86_64.exe"
  - if "%type%"=="Cygwin" C:\cygwin64\setup-x86_64.exe --quiet-mode --no-shortcuts --upgrade-also --root "C:\cygwin64" --local-package-dir "C:\cache\cygwin" --packages cmake,automake,make,gcc-core,gcc-g++,doxygen,graphviz
  # MinGW
  - if "%type%"=="MinGW" if not exist "C:\mingw.7z" appveyor-retry appveyor DownloadFile "http://downloads.sourceforge.net/mingw-w64/x86_64-7.3.0-release-posix-seh-rt_v5-rev0.7z" -FileName "C:\mingw.7z"
  - if "%type%"=="MinGW" 7z x -y -oC:\ "C:\mingw.7z" > nul
  - if "%type%"=="MinGW" set PATH=C:\mingw64\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - if "%type%"=="MinGW" set INCLUDE=C:\mingw64\x86_64-w64-mingw32\include;%INCLUDE%
  # Visual Studio
  - if "%type%"=="VisualStudio" set PATH=C:\Program Files\MiKTeX 2.9\miktex\bin\x64;C:\Program Files\gs\gs9.22\bin;%PATH%
  - if "%type%"=="VisualStudio" set INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um;%INCLUDE%
  - if "%type%"=="VisualStudio" set LIB=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.16299.0\um\x64;%LIB%
  # git
  - '%command% "cmake --version"'
  - '%command% "git config --global user.name "AppVeyor""'
  - '%command% "git config --global user.email "team@appveyor.com""'
  - '%command% "git config --global push.default simple"'
  - git submodule update --init --recursive --remote

# Build scripts
build_script:
  - cd build
  - '%build%'

# Test scripts
test: off
