# Programming language definition
language: cpp

# Build matrix (OS, compiler)
matrix:
  include:
    - os: linux
      compiler: gcc
      env: OS=linux COMPILER=gcc GCC_VERSION=7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - cmake
            - doxygen
            - graphviz
            - binutils-dev
            - uuid-dev
    - os: linux
      compiler: clang
      env: OS=linux COMPILER=clang CLANG_VERSION=6.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - libstdc++-6-dev
            - cmake
            - doxygen
            - graphviz
            - binutils-dev
            - uuid-dev
    - os: osx
      compiler: clang
      env: OS=osx COMPILER=clang
      osx_image: xcode9.2

# Using Trusty environment
sudo: required
dist: trusty

# Branches to build
branches:
  only:
    - master

# Scripts that run before install
before_install:
  # cmake
  - if [ "$OS" == "linux" ]; then curl -sSL https://cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.sh -o install-cmake.sh; fi
  - if [ "$OS" == "linux" ]; then chmod +x install-cmake.sh; fi
  - if [ "$OS" == "linux" ]; then sudo ./install-cmake.sh --prefix=/usr/local --skip-license; fi
  - cmake --version
  # git
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global push.default simple
  # gcc
  - if [ "$OS" != "osx" ] && [ "$COMPILER" = "gcc" ]; then export CC="gcc-${GCC_VERSION}" CXX="g++-${GCC_VERSION}"; fi
  # clang, libc++, libc++abi
  - if [ "$OS" != "osx" ] && [ "$COMPILER" = "clang" ]; then export CC="clang-${CLANG_VERSION}" CXX="clang++-${CLANG_VERSION}"; fi
  # brew, doxygen, graphviz
  - if [ "$OS" == "osx" ]; then brew update; fi
  - if [ "$OS" == "osx" ]; then brew install doxygen; fi
  - if [ "$OS" == "osx" ]; then brew install graphviz; fi
  # OpenSSL
  - if [ "$OS" == "osx" ]; then export OPENSSL_ROOT_DIR=$(brew --prefix openssl); fi

# Build scripts
script: 
  - cd build
  - ./unix.sh

# Don't send notifications on success
notifications:
  email:
    on_success: never
