# Programming language definition
language: cpp

# Build matrix (OS, compiler)
matrix:
  include:
    - os: linux
      compiler: gcc
      env: OS=linux COMPILER=gcc GCC_VERSION=8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - cmake
            - doxygen
            - graphviz
            - binutils-dev
            - python3-pip
            - python3-setuptools
            - uuid-dev
    - os: linux
      compiler: clang
      env: OS=linux COMPILER=clang CLANG_VERSION=8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
            - libstdc++-8-dev
            - cmake
            - doxygen
            - graphviz
            - binutils-dev
            - python3-pip
            - python3-setuptools
            - uuid-dev
    - os: osx
      compiler: clang
      env: OS=osx COMPILER=clang
      osx_image: xcode10.2

# OS environment
sudo: required
dist: xenial

# Branches to build
branches:
  only:
    - master

# Scripts that run before install
before_install:
  # gcc
  - if [ "$OS" != "osx" ] && [ "$COMPILER" = "gcc" ]; then export CC="gcc-${GCC_VERSION}" CXX="g++-${GCC_VERSION}"; fi
  # clang, libc++, libc++abi
  - if [ "$OS" != "osx" ] && [ "$COMPILER" = "clang" ]; then export CC="clang-${CLANG_VERSION}" CXX="clang++-${CLANG_VERSION}"; fi
  # brew, doxygen, graphviz
  - if [ "$OS" == "osx" ]; then brew update; fi
  - if [ "$OS" == "osx" ]; then brew install doxygen; fi
  - if [ "$OS" == "osx" ]; then brew install graphviz; fi
  # cmake
  - cmake --version
  # doxygen support
  - export doxygen=yes
  # git
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global push.default simple
  # gil
  - pip3 install gil
  - gil update

# Build scripts
script: 
  - cd build
  - ./unix.sh

# Don't send notifications on success
notifications:
  email:
    on_success: never
